### ISSUE TITLE
Fix(favicon): Barely visible in darkmode.

### ISSUE THREAD

**Issue by x-N0** [bitcartcc/bitcart-site#3]
![imagen](https://user-images.githubusercontent.com/51316342/92389002-345ee500-f0e6-11ea-9c0e-52ef8bfc1082.png)

site: https://bitcartcc.com/

Posible fix:
- [ ] Add white background.

**Comment by Shadman-Ahmed-Chowdhury** [comment]
I would like to be assigned.

**Comment by MrNaif2018** [comment]
We've now got the favicon prepared, so you can use this one:
https://github.com/bitcartcc/bitcart-media/blob/master/favicon.ico

**Comment by MrNaif2018** [comment]
Closed by #9
