### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-site#5]
Main welcome: bitcartcc/bitcart#133

Issue list:
- [x] Fix favicon barely visible in darkmode (#3)

**Comment by Shadman-Ahmed-Chowdhury** [comment]
I'd like to be assigned. What is required to do? Should I change the color of the favicon?

**Comment by MrNaif2018** [comment]
Hi! Thank you! Yes, basically the favicon would need to have a white background.
See our https://github.com/bitcartcc/bitcart-media/blob/master/logo.svg for reference.
Note: https://github.com/bitcartcc/bitcart-admin/issues/10#issuecomment-701465782
Maybe we will pick the best favicon and upload that to our media repo :D

**Comment by MrNaif2018** [comment]
You may need to comment on #3 for me to be able to assign you to it

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest!
